version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 10080:80
    volumes:
      - ./src/sample:/var/www
  cocomo:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 10081:80
    volumes:
      - ./src/mocomo:/var/www